/*******************************************************************************************
* 
*                                  DO NOT EDIT THIS FILE
* 
* This file was automatically generated, any modification to it will be lost
* 
*******************************************************************************************/

#include <vector>
#include "TensorOps/Scope.h"



using namespace LTSE::TensorOps;
/*******************************************************************************************
* 
*                                  DO NOT EDIT THIS FILE
* 
* This file was automatically generated, any modification to it will be lost
* 
*******************************************************************************************/

std::vector<float> GetWaveformBaselineData();
OpNode GetWaveformBaselineNode(Scope &aScope);
std::vector<float> GetWaveformNoiseData();
OpNode GetWaveformNoiseNode(Scope &aScope);
std::vector<float> GetPostStaticNoiseWaveformData();
OpNode GetPostStaticNoiseWaveformNode(Scope &aScope);
std::vector<uint32_t> GetPacketHeaderData();
std::vector<float> GetWaveformData();
OpNode GetWaveformNode(Scope &aScope);
std::vector<float> GetFilteredWaveformData();
OpNode GetFilteredWaveformNode(Scope &aScope);
std::vector<float> GetThresholdData();
OpNode GetThresholdNode(Scope &aScope);
std::vector<float> GetDistanceData();
OpNode GetDistanceNode(Scope &aScope);
std::vector<float> GetAmplitudeData();
OpNode GetAmplitudeNode(Scope &aScope);
std::vector<uint8_t> GetPulseIsSaturatedData();
OpNode GetPulseIsSaturatedNode(Scope &aScope);
std::vector<float> GetPreSaturationBaselineData();
OpNode GetPreSaturationBaselineNode(Scope &aScope);
std::vector<float> GetPostSaturationBaselineData();
OpNode GetPostSaturationBaselineNode(Scope &aScope);
std::vector<uint32_t> GetSaturatedPulseLengthData();
OpNode GetSaturatedPulseLengthNode(Scope &aScope);
std::vector<float> GetLastUnsaturatedSampleData();
OpNode GetLastUnsaturatedSampleNode(Scope &aScope);
std::vector<float> GetBlinderOutputData();
OpNode GetBlinderOutputNode(Scope &aScope);
std::vector<uint8_t> GetValidDetectionData();
OpNode GetValidDetectionNode(Scope &aScope);
std::vector<uint32_t> GetValidDetectionCountData();
OpNode GetValidDetectionCountNode(Scope &aScope);
std::vector<uint32_t> GetDetectionMetadata();
std::vector<uint32_t> GetPacketTraceData();