application:
  window_properties: {width: 1920, height: 1080, x: 100, y: 100}
  ui:
    font_size: 14
    icon_font: "C:\\GitLab\\SpockEngine\\Resources\\fonts\\fontawesome-webfont.ttf"
    main_font: 
      regular: segoeui.ttf
      bold: segoeuib.ttf
      italic: segoeuii.ttf
      bold_italic: segoeui.ttf
    mono_font: "C:\\GitLab\\SpockEngine\\Resources\\fonts\\dejavu-fonts-ttf-2.37\\ttf\\DejaVuSansMono.ttf"